### ISSUE TITLE
bug(mysql): Failed to connect to MySQL when using `localhost` in the connection string

### ISSUE THREAD

**Issue by detygon** [EPTIC-Solutions/valet-wsl#2]
**Describe the bug**  
I cannot use when `db:*` commands when `localhost` is used in the connection string. I must manually update the `Mysql.php` file to use `127.0.0.1` in the `getConnection` method to make it work.

**To Reproduce**  
1. Fresh install Valet WSL
2. Make sure you can successfully connect to `mysql` via the cmd line
3. Run `valet db:list`

**Expected behavior**  
List the databases.

**Screenshots**  
![image](https://user-images.githubusercontent.com/25983025/176147520-1a2a7259-3081-4d46-8320-358999c08125.png)

**WSL Version (please complete the following information):**  
 - OS: Ubuntu
 - Version: 20.04
 - Package Manager: apt

**Additional Context**
This is the line that is causing the issue. 
![image](https://user-images.githubusercontent.com/25983025/176149165-12c64913-ee35-4d39-954b-46647818463b.png)

**Comment by wizzymore** [comment]
Hi @detygon, are you running your mysql server on windows or in WSL?

**Comment by detygon** [comment]
I'm using WSL, I did not install anything except php. I've let the package do the entire setup.
